create table public.topics
(
    id         bigint generated by default as identity not null,
    created_at timestamp with time zone                not null default now(),
    title      text null,
    constraint topics_pkey primary key (id)
) TABLESPACE pg_default;

create table public.question
(
    id         bigint generated by default as identity not null,
    created_at timestamp with time zone                not null default now(),
    "topicId"  bigint                                  not null,
    title      text null,
    constraint question_pkey primary key (id),
    constraint question_topicId_fkey foreign KEY ("topicId") references topics (id)
) TABLESPACE pg_default;

create table public.question_variant
(
    id          bigint generated by default as identity not null,
    created_at  timestamp with time zone                not null default now(),
    question_id bigint null,
    widget_type text null,
    payload     json null,
    answer      json null,
    constraint question_variant_pkey primary key (id),
    constraint question_variant_question_id_fkey foreign KEY (question_id) references question (id),
    constraint question_variant_widget_type_fkey foreign KEY (widget_type) references widget (type)
) TABLESPACE pg_default;

create table public.widget
(
    type       text                     not null,
    created_at timestamp with time zone not null default now(),
    constraint widget_pkey primary key (type)
) TABLESPACE pg_default;
INSERT INTO "public"."widget" ("type", "created_at")
VALUES ('code-completion', '2026-03-04 21:05:46.416965+00'),
       ('quiz', '2026-03-04 21:02:38.772724+00'),
       ('true-false', '2026-03-04 21:05:13.328367+00');


create table public.user_topics
(
    id           bigint generated by default as identity not null,
    created_at   timestamp with time zone                not null default now(),
    questoin_id  bigint null,
    "isSuccsess" boolean null,
    updated_at   timestamp with time zone null,
    constraint user_topics_questoin_id_fkey foreign KEY (questoin_id) references question_variant (id)
) TABLESPACE pg_default;